### ISSUE TITLE
Allow for not using osa processing database

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/lstosa#221]
https://github.com/cta-observatory/lstosa/blob/db49416fbb65551b0bbe0bfd99f0fbad81fc2bb1/osa/osadb.py#L48

@marialainez, I think we could use the database if the file is defined in the cfg. Otherwise, skip everything related to it. Another way would be to catch the exception of not founding the database and continue otherwise.

When I implemented this, I thought about creating first the DB file if not exist. Another option would be to first create the DB manually with your user using the script `/fefs/aswg/data/real/OSA/database/create_osa_db.py` See also: https://github.com/cta-observatory/lstosa/wiki#osa-database

**Comment by marialainez** [comment]
Ok, I will make a change so that it only writes in the database if it's defined in the cfg

**Comment by morcuended** [comment]
done in #222
