### ISSUE TITLE
Provenance being produced up to DL2 even if --no-dl2 option is used

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/lstosa#225]
Right now, provenance parsing triggered by autocloser is producing provenance products up to DL2 even if `--no-dl2` option is used. This is an unwanted side effect, which should be corrected and avoid the creation of the DL2 directories (only filled with provenance files) in this case.

Check the filters used in script `provprocess.py`

**Comment by morcuended** [comment]
It would be good to fix this. OSA is still producing empty DL2 directories (only provenance products are copied there)

**Comment by marialainez** [comment]
Fixed in #259
