### ISSUE TITLE
Reading in the event ids of interleaved pedestals for LST1 data before July 2020

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/lstosa#95]
This is the new option of the event source in ctapipe_io_lst, added in https://github.com/cta-observatory/ctapipe_io_lst/pull/129, to read in a file containing event ids of interleaved pedestals, so that they can be properly tagged:

```
 pedestal_ids_path = Path(
        exists=True,
        help=(
            'Path to a file containing the ids of the interleaved pedestal events'
            ' for the current input file'
        )
    )
```

The subrun-wise files in question, for all the nights in which I could identify pedestals, are here:

`/fefs/aswg/workspace/abelardo.moralejo/pedestal_finder/YYYYMMDD`

Please look for a convenient place for them. May be a "patches" subdirectory somewhere in the tree?

**Comment by morcuended** [comment]
@moralejo, I remember the location of these files was discussed but I do not know if anything was agreed upon back then. Shall I put it under the monitoring branch (where right now we have all the auxiliary data we use) or should I create a new subdirectory at the same level as DL1, DL2, etc. 

I propose something like `/fefs/aswg/data/real/monitoring/PedestalFinder/YYYYMMDD`

Regarding its usage, I guess we should check if this pedestal_ids file exists and if so we should pass it as an input argument to the r0_to_dl1 script.
